name: Test Action

on: [push]

jobs:
  fish_indent:
    runs-on: ubuntu-latest
    name: Run fish_indent
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: run fish_indent
        id: run_fish_indent
        uses: ./
